version: "3.0"

volumes:
  db-data:
    external: false

services:

  app:
    build: .
    links:
      - "db:mariadb"
    volumes:
      - .:/code
    ports:
      - "8180:8180"
      - "8443:8443"
    depends_on:
      - db
