apiVersion: v1
kind: Service
metadata:
  name: 'steve-service'
  namespace: 'steve'
spec:
  ports:
  - name: steve
    port: 8180
    protocol: TCP
    targetPort: 8180
  selector:
    app: 'steve-deployment'
  sessionAffinity: None
  type: ClusterIP